// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7-jNX8JgjKob5cj_Mzv-AGvvhvlbY50',
    appId: '1:555929582465:web:bb87e3ce8ed4d2a6eac680',
    messagingSenderId: '555929582465',
    projectId: 'foodloop-8b933',
    authDomain: 'foodloop-8b933.firebaseapp.com',
    storageBucket: 'foodloop-8b933.firebasestorage.app',
    measurementId: 'G-7LFLZNBTJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwZwB1TLxA4h8W8qskgKw7OBrI_H0bfc',
    appId: '1:555929582465:android:85d8c29b66dc89b1eac680',
    messagingSenderId: '555929582465',
    projectId: 'foodloop-8b933',
    storageBucket: 'foodloop-8b933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8VBxtLedoaElrEA3saYf_smVnAA5dU-0',
    appId: '1:555929582465:ios:51d9e0e303f05618eac680',
    messagingSenderId: '555929582465',
    projectId: 'foodloop-8b933',
    storageBucket: 'foodloop-8b933.firebasestorage.app',
    iosBundleId: 'com.example.foodloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8VBxtLedoaElrEA3saYf_smVnAA5dU-0',
    appId: '1:555929582465:ios:51d9e0e303f05618eac680',
    messagingSenderId: '555929582465',
    projectId: 'foodloop-8b933',
    storageBucket: 'foodloop-8b933.firebasestorage.app',
    iosBundleId: 'com.example.foodloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7-jNX8JgjKob5cj_Mzv-AGvvhvlbY50',
    appId: '1:555929582465:web:574fa8235c844ee8eac680',
    messagingSenderId: '555929582465',
    projectId: 'foodloop-8b933',
    authDomain: 'foodloop-8b933.firebaseapp.com',
    storageBucket: 'foodloop-8b933.firebasestorage.app',
    measurementId: 'G-4MM5N73WXJ',
  );
}
